BottomPadding = 10
TopPadding = 10
LeftPadding = 10
RightPadding = 10
WinTitle = 28
WinBorder = 5
NavigateAcrossWorkspaces = True  # TODO availabe in Unity7
TempFile = "/dev/shm/.stiler_db"
LockFile = "/dev/shm/.stiler.lock"
